apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Release.Name }}-echo
spec:
  params:
    - name: message
      type: string
      description: output message
      default: Hello Word
  steps:
    - name: echo-message
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/bin/sh
        set -eu -o pipefail
      
        echo $(params.message)