apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Release.Name }}-gogl-build
spec:
  params:
  - name: appdirectory
    type: string
    description: 
    default: .
  - name: appbuildimage
    type: string
    description: 
    default: quay.io/yakiyoshi/gogl:0.0.2
  steps:
  - name: gogl-build
    workingDir: $(workspaces.application.path)
    resources: {}
    image: $(params.appbuildimage)
    script: |
      #!/bin/bash
      set -exu -o pipefail
    
      echo "Building gogl application..."
      ls -la
      cd $(params.appdirectory)
      go build
      ls -la
    env:
      - name: GOPATH
        value: $(workspaces.modules.path)
  workspaces:
  - name: application
    mountPath: /application
  - name: modules
